### ISSUE TITLE
Mermaid diagram is not displayed

### ISSUE THREAD

**Issue by sh-cho** [fluent/fluent-bit-docs#1433]
ex) https://docs.fluentbit.io/manual/concepts/data-pipeline/output

**Comment by esmerel** [comment]
whoops, we'll open a ticket and get that fixed.

**Comment by esmerel** [comment]
Oh hey, you're the person making all the changes and suggestions! Thanks! We have an internal ticketing system that I'm putting this into, so it -will- get fixed. Promise I'm not just closing it on you without following up :D

**Comment by alexakreizinger** [comment]
oh, I didn't realize that mentioning an issue in a PR would automatically close the issue after the PR gets merged!

thanks for opening this issue—it looks like there was a problem with GitBook's configuration settings that disabled Mermaid rendering for all 3.1 docs. fingers crossed that this won't happen again, since I made "Mermaid = enabled" the default for all current and future branches :)

**Comment by sh-cho** [comment]
Looks like Gitbook doesn't rebuild if content is same as before? Only [Buffer](https://docs.fluentbit.io/manual/concepts/data-pipeline/buffer)'s diagram is updated 🥲

**Comment by alexakreizinger** [comment]
🤦thanks for catching that. I'll open another PR to force a refresh on all the other pages with Mermaid diagrams...

**Comment by alexakreizinger** [comment]
alright, I refreshed all the pages this time, and it looks like the diagrams are rendering correctly now... fingers crossed they stay that way 😅
