### ISSUE TITLE
1.7 releases on windows 10 may lost some file

### ISSUE THREAD

**Issue by markxp** [fluent/fluent-bit-docs#480]
I tried x64 binary installer and zip file, after installed (unzipped) and run the test process:

`> .\path_to_flb\fluent-bit.exe -i dummy -o stdout`

... and nothing on screen. After retry it on windows command line tool,
it pops errors which said  missing "libcrypto-1_1-x64.dll" and "libssl-1_1-x64.dll" files.

This issue does not occured in 1.6.

**Comment by fujimotos** [comment]
> ... and nothing on screen. After retry it on windows command line tool,
> it pops errors which said missing "libcrypto-1_1-x64.dll" and "libssl-1_1-x64.dll" files.

@markxp This is probably due to the switch to OpenSSL in v1.7.0.

Before 1.6, we used mbedTLS and statically linked it to `fluent-bit.exe`
so that Fluent Bit works without any DLL dependencies.

Probably we should find some way to static link OpenSSL to the windows build
as well, considering that not many Windows users have OpenSSL installed
in their system.

**Comment by markxp** [comment]
here's related issue [fluent bit 3160](https://github.com/fluent/fluent-bit/issues/3160)

**Comment by fujimotos** [comment]
@markxp FWIW, I posted fluent/fluent-bit#3193 that enables static
linking of OpenSSL on Windows builds.

Your issue should be resolved once that fix lands on mainline.

**Comment by agup006** [comment]
That fix should be in mainline, as a reminder - please open these issues in the fluent-bit repo vs. the docs repo
